#!/usr/bin/env bash
#Prints 'bad luck' in 4th loop iteration; 'good luck' in 8th loop iteration; 'Best School' for the remaining iterations
i=1; while [ $i -le 10 ]
     do
	     if [ $i -eq 4 ]
	     then
		     echo "bad luck"
	     elif [ $i -eq 8 ]
	     then
		     echo "good luck"
	     else
		     echo "Best School"
	     fi
	     ((i++))
done
